# Changes here will be overwritten by Copier
_commit: v0.0.93-7-gca8fce3
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: A web app that is hosted within a local intranet. Nuxt frontend, python
    backend, docker-compose
install_claude_cli: false
python_ci_versions:
- 3.12.7
- 3.13.2
python_version: 3.12.7
repo_name: copier-nuxt-python-intranet-app
repo_org_name: LabAutomationAndScreening
repo_org_name_for_copyright: Lab Automation & Screening
ssh_port_number: 15173
template_might_want_to_install_aws_ssm_port_forwarding_plugin: true
template_might_want_to_use_python_asyncio: true
template_might_want_to_use_vcrpy: true
template_uses_javascript: true
template_uses_pulumi: false
template_uses_python: true
template_uses_vuejs: true

