# Changes here will be overwritten by Copier
_commit: v0.0.18-8-g1e7140e
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: A web app that is hosted within a local intranet. Nuxt frontend, python
    backend, docker-compose
install_aws_ssm_port_forwarding_plugin: false
python_ci_versions:
- 3.12.7
- 3.13.2
python_version: 3.12.7
repo_name: copier-nuxt-python-intranet-app
repo_org_name: LabAutomationAndScreening
ssh_port_number: 65425
template_uses_javascript: true
template_uses_pulumi: false
template_uses_python: true
template_uses_vuejs: true

