# ============== WARNING ==============================================================================
# File is managed by copier template: gh:LabAutomationAndScreening/copier-base-template.git
# See .copier-managed-files.json for details.
#
# You are welcome to make changes to this file in your repo if they are custom to your project,
# but if the change should be shared with other projects, please backport it to the template repo.
# =====================================================================================================
[src]
exclude = [
    # excludes managed by this repository

    "**/template/**", # without the dependencies of the template installed, running pyright on them within the copier template is not useful


    # excludes managed by template
    "**/node_modules",
    "**/.precommit_cache",
    "**/.ruff_cache",
    "**/.npm_cache",
    "**/.pipx_cache",
    "**/__pycache__",
    "**/vendor_files",
    "**/generated/graphql",
    "**/generated/open_api",
    "**/.venv",
    "**/venv",
    "**/copier_template_resources"
]
